# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.7
    hooks:
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix]
      - id: ruff-format
        types_or: [python, pyi, jupyter]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.11.1"
    hooks:
      - id: mypy
        additional_dependencies: ['numpy >= 1.22', "ml-dtypes >= 0.1", "pytest"]
        args: [--show-error-codes]
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: "v18.1.5"
    hooks:
      - id: clang-format
  - repo: https://github.com/MarcoGorelli/cython-lint
    rev: v0.16.2
    hooks:
      - id: cython-lint
      - id: double-quote-cython-strings
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.8.0-1
    hooks:
      - id: shfmt
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
  # - repo: https://github.com/cheshirekow/cmake-format-precommit
  #   rev: v0.6.10
  #   hooks:
  #     - id: cmake-format
  #     - id: cmake-lint
